---
# Connection Settings
ansible_user: "medusa"
ansible_port: 22  # Explicitly declare default port
ansible_ssh_private_key_file: "~/.ssh/id_rsa"  # Best practice for key-based auth

# SSH Tuning (Security + Performance)
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=accept-new
  -o ConnectTimeout=15
  -o ControlMaster=auto
  -o ControlPersist=60s
  -o ServerAliveInterval=30

# Privilege Escalation
ansible_become: true
ansible_become_method: "sudo"
ansible_become_user: "root"
ansible_become_flags: "--preserve-env"  # Keep environment variables

# Timeouts (Adjusted for modern infra)
ansible_timeout: 30  # General timeout
ansible_ssh_timeout: 15  # SSH-specific
ansible_command_timeout: 300  # Reduced from 600s

# Python Configuration
ansible_python_interpreter: "auto_silent"  # Better than hardcoded path
ansible_python_interpreter_auto: silent  # Fallback behavior

# Performance Tuning
ansible_ssh_pipelining: true
ansible_ssh_args: "-C -o CompressionLevel=5"  # Compression for slow links
ansible_gathering: smart  # Only gather relevant facts
