- hosts: all
  become: true

  tasks:
    - name: Update and Upgrade APT Packages
      apt:
        upgrade: yes
        update_cache: yes
        become: true
      ignore_errors: yes  # Optionally, to not fail the playbook on errors
