---
- name: Apply base configuration to all systems
  hosts: all
  vars_files:
    - "../environments/{{ env | default('prod') }}.yml"
  
  # Explicitly declare we want to gather facts for virtualization checks
  gather_facts: true
  
  pre_tasks:
    - name: Validate environment file exists
      assert:
        that: env is defined or lookup('file', '../environments/prod.yml') != ''
        fail_msg: "Environment file missing. Set 'env' variable or ensure prod.yml exists"
        quiet: yes
  
  roles:
    - role: common
      tags: [common, always]
  
  post_tasks:
    - name: Verify base installation
      command: which {{ item }}
      loop: [curl, git, vim]
      changed_when: false
      tags: [validation, always]
  
  tags:
    - base
    - always
