---
- name: Ensure exact package set is installed
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes
    autoremove: yes  # Automatically removes orphaned dependencies
    purge: yes       # Completely removes config files when uninstalling
  tags: [packages]