---
- name: Apply base configuration
  hosts: all
  vars_files:
    - "{{ playbook_dir }}/../environments/{{ env | default('prod') }}.yml"
    - "{{ playbook_dir }}/../group_vars/all.yml"  # Load global vars

  roles:
    - role: common
      tags: always