---
- name: Apply base configuration
  hosts: all
  become: yes
  vars:
    env: "{{ semaphore_environment | default('prod') }}"  # Semaphore will pass this
    
  vars_files:
    - "{{ playbook_dir }}/../environments/{{ env }}.yml"  # Environment overrides
    
  roles:
    - role: common
      tags: [base, packages]