---
- name: Apply base configuration to all systems
  hosts: all
  become: yes  # Ensures root privileges for package management
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all.yml"
    - "{{ playbook_dir }}/../environments/{{ env | default('prod') }}.yml"

  vars:
    env: "{{ env | default('prod') }}"  # Explicit environment variable
    ansible_python_interpreter: "{{ ansible_python_interpreter | default('auto_silent') }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default(ansible_ssh_private_key_file, true) }}"

  pre_tasks:
    - name: Validate connection parameters
      assert:
        that:
          - ansible_user is defined
          - ansible_ssh_private_key_file is defined or ansible_password is defined
        fail_msg: "Missing required connection parameters"
      tags: always

  roles:
    - role: common
      tags: [base, common, always, packages]  # Added 'packages' tag for targeted runs

  post_tasks:
    - name: Verify base connectivity
      ansible.builtin.ping:
      changed_when: false
      tags: [validation, always]