---
- name: Apply base configuration to all systems
  hosts: all
  vars_files:
    - "{{ playbook_dir }}/../environments/{{ env | default('prod') }}.yml"
  
  # Critical path configuration for Semaphore
  vars:
    ansible_roles_path: "{{ playbook_dir }}/../../roles"
  
  roles:
    - role: common
      tags: always
  tags:
    - base
    - always
